add wave  \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/XLEN \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/clk_i \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/rst_ni \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/flush_i \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/bitmanip_exception_o \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/fu_data_i \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/bitmanip_valid_i \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/bitmanip_ready_o \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/bitmanip_trans_id_o \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/bitmanip_valid_o \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/bitmanip_result_o \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/clock \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/reset \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/din_valid \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/din_ready \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/din_decoded \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/din_rs1 \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/din_rs2 \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/din_rs3 \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/dout_valid \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/dout_ready \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/dout_rd \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/trans_id \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_trans_id_d \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_trans_id_s \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_trans_id_d \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_trans_id_s \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/op_select \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_op_select \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/stall \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/insn_bextdep \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/insn_bitcnt \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/insn_bmatxor \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/insn_clmul \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/insn_crc \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/insn_shifter \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/insn_simple \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_bextdep \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_bitcnt \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_bmatxor \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_clmul \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_crc \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_shifter \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_simple \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_bextdep_ready \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_bitcnt_ready \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_bmatxor_ready \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_clmul_ready \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_crc_ready \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_shifter_ready \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_simple_ready \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_rs1 \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_rs2 \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/in_rs3 \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_bextdep \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_bitcnt \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_bmatxor \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_clmul \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_crc \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_shifter \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_simple \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_bextdep_valid \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_bitcnt_valid \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_bmatxor_valid \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_clmul_valid \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_crc_valid \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_shifter_valid \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_simple_valid \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_ready \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/output_valid \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/output_value \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/busy \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/busy_reg \
sim:/ariane_bitmanip_tb/dut/i_ariane/ex_stage_i/bitmanip_unit_i/out_any_valid
